name: Deploy to Azure Web App (.NET)

on:
  push:
    branches: [ "main" ]   # deploy hver gang du pusher til main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: PlayGrounds
  PROJECT_PATH: ./PlayGroundController/PlayGroundController.csproj
  DOTNET_VERSION: "9.0.x"
  PUBLISH_DIR: ./published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - run: dotnet restore "${{ env.PROJECT_PATH }}"
      - run: dotnet build "${{ env.PROJECT_PATH }}" --configuration Release --no-restore
      - run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release -o "${{ env.PUBLISH_DIR }}" /p:UseAppHost=false

      - uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}

      - run: echo "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
